version: "3"
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 50000:50000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/demo

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 31019:4200
    depends_on:
      - backend

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    user: "999:999"

volumes:
  postgres_data:
